### ISSUE TITLE
Why can't language be changed?

### ISSUE THREAD

**Issue by algodave** [xyu/heroku-wp#31]
I deployed Wordpress to Heroku really straightforward thanks to this cool project!
However, I need to create a blog in Italian and I was expecting to be able to change the site language in the admin panel (as I've done on a previous 4.1 install of mine), but only English was selectable:

![screen shot 2015-03-09 at 16 50 10](https://cloud.githubusercontent.com/assets/2955556/6558514/e2c7951e-c67c-11e4-8bdb-c396ccf56197.png)

I also tried to comment [wp-config.php#L134](https://github.com/xyu/heroku-wp/blob/master/public/wp-config.php#L134) but no luck.

Is that because Wordpress is installed as a composer package? I have another WP Heroku deploy which is using the 4.1 branch on github, and I was able to select among all languages there.

Thank you!

**Comment by xyu** [comment]
This is because WP is set to [read-only mode](https://github.com/xyu/heroku-wp/blob/master/public/wp-config.php#L17-L19) which disables the ability of WP from downloading language packs on demand. This is done because the Heroku dyno FS should be considered temporary / ephemeral. As new dynos are spun up and down any data downloaded to a single dyno will not exist on any of the others.

It looks like language packs are not going to be supported by wpackagist (outlandishideas/wpackagist#37) which means to fix this some sort of post install script will need to be used to get composer to grab additional language packs.

**Comment by algodave** [comment]
Thank you for explaining :)

**Comment by xyu** [comment]
@algodave so after thinking about this I think the best way to go about this is to manually commit the language files into the cloned repo. I have not tried it however the following should work.

Create `public/wp-content/languages` then download the `.mo` file for the lang you want (http://wpcentral.io/internationalization/) into it and comment.

If you want to give this a try and it works would you mind updating the README with this information and sending in a pull request?

Thanks!

**Comment by xyu** [comment]
Closing this issue as #31 explains how to add languages.
