### ISSUE TITLE
"bash: wp: command not found"

### ISSUE THREAD

**Issue by samkleeman1** [xyu/heroku-wp#61]
I have run this package exactly as described in the readme but I get this error every time
Any thoughts?

**Comment by xiangming** [comment]
@samkleeman1 
Could you please tell me the solution? I'm getting the same error.

**Comment by samkleeman1** [comment]
I believe this issue is to do with this part of the init.sh file failing

`	cd .. && \
	git checkout -b "$1" && \
	bin/composer update --ignore-platform-reqs && \
	git add composer.lock && \
	git commit -m "Initial commit for '$1'" && \
	git push heroku "$1:master"`

I think I did `git add .` and then set what my default repository was first e.g. `heroku git:remote -a falling-wind-1624` in the console and that fixed it

**Comment by xiangming** [comment]
@samkleeman1 Thanks, it's helpfull.

@xyu I think you should reopen this issue, there are some problem when `Do the intial commit for this site` in `init.sh`

**Comment by xyu** [comment]
@xiangming thanks for the ping; yeah going to reopen this and checkout what the issue is.

**Comment by learning-more** [comment]
When I run the command:
`cd heroku-wp && bin/init.sh thieves4`
The init script runs, and ends with the error: 
`fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Deploy failed for 'thieves4'.
`

Based on [what I read here](https://devcenter.heroku.com/articles/git#creating-a-heroku-remote):

> "If you’re working out of another branch locally, you can either merge to master before pushing, or specify that you want to push your local branch to a remote master. To push a branch other than master, use this syntax (above)"

So, it seems we are not merging to master first. The init.sh is attempting to push my local branch to a master, but it fails as the remote named "heroku" is not configured correctly.
Perhaps the remote should be specified differently before the push command?

**Comment by xyu** [comment]
So in theory the `heroku apps:create ...` command should have added a `heroku` remote to your local git repo [Heroku docs](https://devcenter.heroku.com/articles/creating-apps#creating-a-named-app).

These errors seems to indicate that this sometimes fails however I have not been able to reproduce it yet. @learning-more do you still happen to have the full logs when you ran the init script?

**Comment by jamiegoodwin** [comment]
In case anyone else finds this from Google like I did, I had the same error but it was because I hadn't added my SSH key to Heroku and the git remote command in init.sh uses --ssh-git. I fixed it by:

Adding my SSH key: https://devcenter.heroku.com/articles/keys#adding-keys-to-heroku

Deleting my existing app (the one I'd created that ran into the error), deleting the Git repo and re-running from scratch (or you'll get errors when trying to checkout your branch).

You can delete the broken Heroku app with:

heroku apps:delete your-app-name

Then just delete the entire heroku-wp folder and follow the guide again. Hopefully this helps :-)
