### ISSUE TITLE
Setting WP salts with /dev/random

### ISSUE THREAD

**Issue by camic** [xyu/heroku-wp#71]
NEW_RELIC_APP_NAME: Heroku WP
Setting WP salts with /dev/random

last output : Setting WP salts with /dev/random
script does not return.

**Comment by punggolzenith** [comment]
This is actually a /dev/random issue try googling it. There is not enough "entropy" in the system. Try downloading a large file in the background.

**Comment by PhamBaTrungThanh** [comment]
And how exactly can we do that?

**Comment by punggolzenith** [comment]
bro, like i say, try googling.

when it hangs at /dev/random, u try to open a browser tab and download any random file

**Comment by xyu** [comment]
@punggolzenith is correct, in order to make your WordPress install more secure I've set this to use `/dev/random` to generate the salts. The downside is this is "blocking" meaning it does not return until it is able to get enough randomness. Moving around a mouse cursor, downloading a large file, using the wifi or even walking around with the laptop (if that's what you're using) is normally enough to get more random data from the environment around you.
